In [1]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = 'https://www.worldometers.info/world-population/population-by-country/'

In [5]:
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

In [8]:
table = soup.find('table', 'datatable w-full border border-zinc-200')

In [10]:
world_column = table.find_all('th')

In [12]:
column_titles = [column.text for column in world_column]
print(column_titles)

[' # ', ' Country (or dependency) ', ' Population 2026 ', ' Yearly Change ', ' Net Change ', ' Density (P/KmÂ²) ', ' Land Area (KmÂ²) ', ' Migrants (net) ', ' Fert. Rate ', ' Median Age ', ' Urban Pop % ', ' World Share ']

In [13]:
import pandas as pd

In [15]:
df = pd.DataFrame(columns = column_titles)

In [28]:
df

Empty DataFrame
Columns: [ # ,  Country (or dependency) ,  Population 2026 ,  Yearly Change ,  Net Change ,  Density (P/KmÂ²) ,  Land Area (KmÂ²) ,  Migrants (net) ,  Fert. Rate ,  Median Age ,  Urban Pop % ,  World Share ]
Index: []

In [22]:
world_row = table.find_all('tr')

In [32]:
for rows in world_row[1:]:
    row_data = rows.find_all('td')
    individual_row = [data.text for data in row_data]
    
    length = len(df)
    df.loc[length] = individual_row 
df

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","â440,456",1.93,29.2,37.6%,17.79%
1,2,China,"1,412,914,089",â0.22%,"â3,182,005",150,"9,388,211","â232,107",1.03,40.6,68.7%,17.02%
2,3,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.20%
3,4,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","â39,472",2.08,30.7,60.3%,3.47%
4,5,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","â1,144,738",3.44,20.8,34.7%,3.12%
...,...,...,...,...,...,...,...,...,...,...,...,...
229,230,Montserrat,"4,328",â0.71%,â31,43,100,â10,1.45,41.8,11.7%,0.000052%
230,231,Falkland Islands,"3,465",â0.12%,â4,0,"12,170",â16,1.69,43.4,68.4%,0.000042%
231,232,Tokelau,"2,691",3.18%,83,269,10,43,2.54,27.6,â,0.000032%
232,233,Niue,"1,822",0.05%,1,7,260,2,2.44,35.1,45.2%,0.000022%
233,234,Holy See,506,1%,5,"1,265",0,13,1,56.2,â,0.0000061%

In [33]:
df.to_csv(r'C:\Users\sophi\Documents\Python lessons\csv_folder\world_population', index = False)

In [3]:
url = 'https://www.worldometers.info/world-population/population-by-country/'

In [5]:
page = requests.get(url)

In [6]:
soup = BeautifulSoup(page.text, 'html')

In [9]:
table = soup.find('table', "datatable w-full border border-zinc-200")

In [17]:
table_headers = table.find_all('th')

In [18]:
column_names = [header.text for header in table_headers]

In [19]:
print(column_names)

[' # ', ' Country (or dependency) ', ' Population 2026 ', ' Yearly Change ', ' Net Change ', ' Density (P/KmÂ²) ', ' Land Area (KmÂ²) ', ' Migrants (net) ', ' Fert. Rate ', ' Median Age ', ' Urban Pop % ', ' World Share ']

In [20]:
import pandas as pd

In [25]:
df = pd.DataFrame(columns = column_names)
df

Empty DataFrame
Columns: [ # ,  Country (or dependency) ,  Population 2026 ,  Yearly Change ,  Net Change ,  Density (P/KmÂ²) ,  Land Area (KmÂ²) ,  Migrants (net) ,  Fert. Rate ,  Median Age ,  Urban Pop % ,  World Share ]
Index: []

In [27]:
table_rows = table.find_all('tr')

In [36]:
for rows in table_rows[1:]:
    table_data = rows.find_all('td')
    individual_table = [data.text for data in table_data]   
    length = len(df)
    df.loc[length] = individual_table

In [38]:
df

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","â440,456",1.93,29.2,37.6%,17.79%
1,2,China,"1,412,914,089",â0.22%,"â3,182,005",150,"9,388,211","â232,107",1.03,40.6,68.7%,17.02%
2,3,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.20%
3,4,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","â39,472",2.08,30.7,60.3%,3.47%
4,5,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","â1,144,738",3.44,20.8,34.7%,3.12%
...,...,...,...,...,...,...,...,...,...,...,...,...
229,230,Montserrat,"4,328",â0.71%,â31,43,100,â10,1.45,41.8,11.7%,0.000052%
230,231,Falkland Islands,"3,465",â0.12%,â4,0,"12,170",â16,1.69,43.4,68.4%,0.000042%
231,232,Tokelau,"2,691",3.18%,83,269,10,43,2.54,27.6,â,0.000032%
232,233,Niue,"1,822",0.05%,1,7,260,2,2.44,35.1,45.2%,0.000022%
233,234,Holy See,506,1%,5,"1,265",0,13,1,56.2,â,0.0000061%